PEP 636: add missing @dataclass
otherwise, on trying this example

>>> where_is(Point(x=0, y=42))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Point() takes no arguments